[project]
name = 'gor'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.gor]
path = 'contracts/gor.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
